# Generated by Django 5.0.1 on 2024-02-15 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0002_story_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='our_story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('story_headline', models.CharField(max_length=200)),
                ('story_title', models.CharField(max_length=200)),
                ('story_description', models.CharField(max_length=1000)),
            ],
        ),
    ]
