# Generated by Django 5.0.1 on 2024-02-16 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0003_our_story'),
    ]

    operations = [
        migrations.CreateModel(
            name='our_mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mission_title', models.CharField(max_length=200)),
                ('mission_description', models.CharField(max_length=200)),
                ('mission_theme', models.CharField(max_length=200)),
                ('mission_semantic', models.CharField(max_length=200)),
            ],
        ),
    ]
