# Generated by Django 5.0.1 on 2024-02-17 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0004_our_mission'),
    ]

    operations = [
        migrations.CreateModel(
            name='founder_donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_title', models.IntegerField()),
                ('founded_title', models.CharField(max_length=200)),
                ('founded_reg', models.CharField(max_length=200)),
                ('donation_title', models.CharField(max_length=200)),
            ],
        ),
    ]
