# Generated by Django 5.0.1 on 2024-02-17 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0005_founder_donation'),
    ]

    operations = [
        migrations.CreateModel(
            name='founding_partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('founding_image', models.ImageField(blank=True, null=True, upload_to='founding_partner/')),
                ('name_founding', models.CharField(max_length=200)),
                ('founding_info1', models.CharField(max_length=1000)),
                ('founding_info2', models.CharField(max_length=1000)),
                ('twiter_link', models.CharField(max_length=500)),
                ('facebook_link', models.CharField(max_length=500)),
                ('instagram_link', models.CharField(max_length=500)),
            ],
        ),
    ]
