# Generated by Django 5.0.1 on 2024-02-20 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0007_founding_par_delete_founding_partner'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
    ]
