# Generated by Django 5.0.1 on 2024-02-22 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0008_slider_is_delete'),
    ]

    operations = [
        migrations.CreateModel(
            name='volinteer_donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('impact_title', models.CharField(max_length=200)),
                ('save_live', models.CharField(max_length=200)),
                ('make_donation', models.CharField(max_length=200)),
                ('be_volunteer', models.CharField(max_length=200)),
            ],
        ),
    ]
