# Generated by Django 5.0.1 on 2024-02-22 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0009_volinteer_donation'),
    ]

    operations = [
        migrations.CreateModel(
            name='casuse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('casuse_headline', models.CharField(max_length=200)),
                ('casuse_image', models.ImageField(blank=True, null=True, upload_to='casuse_image/')),
                ('casuse_title', models.CharField(max_length=200)),
                ('casuse_description', models.CharField(max_length=1000)),
                ('casuse_raised', models.CharField(max_length=200)),
                ('raised_amount', models.CharField(max_length=200)),
                ('casuse_goal', models.CharField(max_length=200)),
                ('goal_amount', models.CharField(max_length=200)),
            ],
        ),
    ]
