# Generated by Django 5.0.1 on 2024-02-22 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0010_casuse'),
    ]

    operations = [
        migrations.RenameField(
            model_name='casuse',
            old_name='casuse_headline',
            new_name='casuse_link',
        ),
    ]
