# Generated by Django 5.0.1 on 2024-02-22 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0011_rename_casuse_headline_casuse_casuse_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='casuse_headline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('casuse_hed', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='casuse',
            name='goal_amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='casuse',
            name='raised_amount',
            field=models.IntegerField(),
        ),
    ]
