# Generated by Django 5.0.1 on 2024-02-24 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0012_casuse_headline_alter_casuse_goal_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='welcome',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
    ]
