# Generated by Django 5.0.1 on 2024-02-26 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0013_welcome_is_delete'),
    ]

    operations = [
        migrations.AddField(
            model_name='image_01',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
    ]
