# Generated by Django 5.0.1 on 2024-02-28 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0014_image_01_is_delete'),
    ]

    operations = [
        migrations.CreateModel(
            name='volunteer_about',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_tit', models.CharField(max_length=200)),
                ('about_desc', models.CharField(max_length=200)),
                ('about_image', models.ImageField(blank=True, null=True, upload_to='casuse_image/')),
            ],
        ),
    ]
